### ISSUE TITLE
ETYPE = "GUIDE" only after SAVE

### ISSUE THREAD

**Issue by chyan26** [chyan26/RaptorServ#2]
The only case when the raptorServ creates fits files with ETYPE = "GUIDE" is after a user manually writes:
SAVE <nb frames> <comment>
and there is only one fits file created with this FITS keyword.

When the viewing analysis is in operation, it gets fits files from the fits pipe on stdin so this software shall filter which files to process or not.  Selecting files with ETYPE = "GUIDE" seems to be a good thing to do, provided the raptorServ creates fits files with ETYPE = "GUIDE" during guiding, which is not the case currently (ETYPE is always IMAGING except once after a SAVE command).

**Comment by marila31** [comment]
Tested not ok:
serv_info->fits_comment = cli_strdup("GUIDING");
to be corrected to "GUIDE"

**Comment by marila31** [comment]
After correcting GUIDING to GUIDE, the patch is still not ok because of this statement:
   if ((serv_info->fits_comment != NULL) &&
       (serv_info->frame_sequence >= serv_info->frame_save_count)) {
      free(serv_info->fits_comment);
      serv_info->fits_comment = NULL;
      serv_info->frame_save_count = 0;
      serv_info->frame_sequence = 0;
   }
That resets the fits_comment.
To be corrected on raptorServ.c
